# Site-wide generic info (overridable per-page)
title: ahoneybun.net
description: Aaron Honeycutt's website
author: Aaron Honeycutt
theme-color: "#002e99"
image: https://ahoneycutt.me/images/card.png

# Site-wide hardcoded (non-overridable by pages)
url: https://ahoneybun.net
# baseurl: /
made-in: Colorado
birthday: '1992-12-31 00:08:00 -0600'

# Site-wide social info
donate: https://ahoneycutt.me/pay
email: aaronhoneycutt@pm.me
github_user: ahoneybun # user with no @
gitlab_user: ahoneybun # user with no @
gravatar: a112b4952ec7f583808683b2b289d2be # Gravatar md5 hash
instagram: athoneycutt # user with no @
pixelfed: "https://pixelfed.social/ahoneybun" # whole URL since it's federated
mastodon: "https://hachyderm.io/@ahoneybun" # whole URL since it's federated
steam: ahoneybun # user/alias, no @
twitch: ahoneybunn
youtube: ahoneybunn
twitter: "@fishfulpenguin" # user including @

# Mastodon-powered commenting. Values can be overridden in front-matter, e.g.
# for multi-author blogs or guest posts.
comments:
  # Your Mastodon API host; this should be where you have an account
  host: hachyderm.io
  # Optional; vanity domain if configured; host will be used if omitted; UNIMPLEMENTED
  #domain: blaede.family
  # Used to determine who the original/verified poster is; role may be expanded
  # in the future (e.g. for moderation)
  username: ahoneybun
  # Additional verified usernames in username@example.com format. If they are on
  # the host listed above, OMIT the @example.com; UNIMPLEMENTED
  verified:
    - btkostner@mastodon.social
    - lizkecso@mastodon.social
    - ryanleesipes@mastodon.social
    - DaisyLee@mastodon.social
    - codemonkeymike@fosstodon.org

# Settings
permalink: /blog/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

collections:
  products:
    output: true
    permalink: /store/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
 - jekyll-feed
 - jekyll-redirect-from
